name: test
description: A test app for TermStyle!
version: 1.0.0
homepage: https://github.com/iamtheblackunicorn/TermStyle
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  harpo:
    git: git://github.com/iamtheblackunicorn/TermStyle.git
dev_dependencies:
  harpo:
    git: git://github.com/iamtheblackunicorn/TermStyle.git
